[Node]
IPCPath = "opera.ipc"
HTTPHost = ""
HTTPPort = 18545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "ftm", "dag", "sfc", "abft", "web3"]
WSHost = ""
WSPort = 18546
WSModules = ["eth", "ftm", "dag", "sfc", "abft", "web3"]
GraphQLVirtualHosts = ["localhost"]

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
DiscoveryV5 = true
BootstrapNodes = []
BootstrapNodesV5 = ["enode://03c70d4597d731ef182678b7664f2a4a3add07056f23d4e01aba86f066080d18fa13abbd2e13e9d4ea762a2715a983b5ac6151162d05ee0434f1847da1a626e9@34.242.220.16:5050", "enode://01c64d1a9dd8a65c56f2d4e373795eb6efd27b714b2b5999363a42a0edc39d7417a431416ceb5c67b1a170983af109e8a15d0c2d44a2ac41ecfb5c23c1a1a48a@3.35.200.210:5050", "enode://7044c88daa5df059e2f7a2667471a8149a5cf66e68643dcb86f399d48c4ff6475b73ee91486ea830d225f7f78a2fdf955208673da51c6852230c3a90a3701c06@3.1.103.70:5050", "enode://594d26c2338566daca9391d73f1b1821bb0b454e6f3d48715116bf42f320924d569534c143b640feec8a8eaa137a0b822426fb62b52a90162270ea5868bdc37c@18.138.254.181:5050", "enode://339e331912e5239a9e13eb82b47be58ea4d3946e91caa2992103a8d4f0226c1e86f9134822d5b238f25c9cbdd473f806caa8e4f8ef1748a6c66395f4bf0dd569@54.66.206.151:5050", "enode://563b30428f48357f31c9d4906ca2f3d3815d663b151302c1ba9d58f3428265b554398c6fabf4b806a49525670cd9e031257c805375b9fdbcc015f60a7943e427@3.213.142.230:7946", "enode://8b53fe4410cde82d98d28697d56ccb793f9a67b1f8807c523eadafe96339d6e56bc82c0e702757ac5010972e966761b1abecb4935d9a86a9feed47e3e9ba27a6@3.227.34.226:7946", "enode://1703640d1239434dcaf010541cafeeb3c4c707be9098954c50aa705f6e97e2d0273671df13f6e447563e7d3a7c7ffc88de48318d8a3cc2cc59d196516054f17e@52.72.222.228:7946"]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":5050"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Opera]
TxIndex = true
DecisiveEventsIndex = false
EventLocalTimeIndex = false
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""
ExtRPCEnabled = false
RPCLogsBloom = true

[Opera.Emitter]
MaxTxsPerAddress = 10
MaxParents = 0
LimitedTpsThreshold = 3360000
NoTxsThreshold = 840000
EmergencyThreshold = 140000

[Opera.Emitter.Validator]
ID = 0

[Opera.Emitter.Validator.PubKey]
Type = 0
Raw = []

[Opera.Emitter.EmitIntervals]
Min = 100000000
Max = 600000000000
Confirming = 110000000
ParallelInstanceProtection = 60000000000
DoublesignProtection = 1620000000000

[Opera.TxPool]
Locals = []
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1
PriceBump = 10
AccountSlots = 16
GlobalSlots = 1536
AccountQueue = 16
GlobalQueue = 384
Lifetime = 10800000000000

[Opera.Protocol]
LatencyImportance = 60
ThroughputImportance = 40
MsgsSemaphoreTimeout = 10000000000
ProgressBroadcastPeriod = 10000000000
MaxInitialTxHashesSend = 20000
MaxRandomTxHashesSend = 128
RandomTxHashesSendPeriod = 20000000000

[Opera.Protocol.EventsSemaphoreLimit]
Num = 10000
Size = 31457280

[Opera.Protocol.MsgsSemaphoreLimit]
Num = 1000
Size = 31457280

[Opera.Protocol.Processor]
EventsSemaphoreTimeout = 10000000000
MaxUnorderedInsertions = 0

[Opera.Protocol.Processor.EventsBufferLimit]
Num = 3250
Size = 11534336

[Opera.Protocol.DagFetcher]
ForgetTimeout = 60000000000
ArriveTimeout = 4000000000
GatherSlack = 100000000
HashLimit = 10000
MaxBatch = 512
MaxParallelRequests = 192
MaxQueuedBatches = 32

[Opera.Protocol.TxFetcher]
ForgetTimeout = 60000000000
ArriveTimeout = 1000000000
GatherSlack = 100000000
HashLimit = 10000
MaxBatch = 512
MaxParallelRequests = 64
MaxQueuedBatches = 32

[Opera.Protocol.StreamLeecher]
RecheckInterval = 1000000000
BaseProgressWatchdog = 5000000000
BaseSessionWatchdog = 150000000000
MinSessionRestart = 5000000000
MaxSessionRestart = 240000000000

[Opera.Protocol.StreamLeecher.Session]
RecheckInterval = 10000000
ParallelChunksDownload = 6

[Opera.Protocol.StreamLeecher.Session.DefaultChunkSize]
Num = 500
Size = 524288

[Opera.Protocol.StreamSeeder]
SenderThreads = 8
MaxSenderTasks = 128
MaxPendingResponsesSize = 67108864
MaxResponseChunks = 12

[Opera.HeavyCheck]
MaxQueuedBatches = 128
MaxBatch = 8
Threads = 0

[Opera.GPO]
Blocks = 20
Percentile = 60
MaxPrice = 1000000000000000

[Opera.VersionWatcher]
ShutDownIfNotUpgraded = false
WarningIfNotUpgradedEvery = 5000000000

[OperaStore]
MaxNonFlushedSize = 23068672
MaxNonFlushedPeriod = 1800000000000

[OperaStore.Cache]
EventsNum = 5000
EventsSize = 6291456
BlocksNum = 1000
BlocksSize = 524288

[OperaStore.EVM.Cache]
ReceiptsSize = 65536
ReceiptsBlocks = 1000
TxPositions = 5000
EvmDatabase = 16777216

[LachesisStore.Cache]
RootsNum = 1000
RootsFrames = 100

[VectorClock.Fc.Caches]
ForklessCausePairs = 20000
HighestBeforeSeqSize = 163840
LowestAfterSeqSize = 163840

[VectorClock.Caches]
HighestBeforeTimeSize = 163840
